# Libraries and Functions

## Import relevant libraries

In [1]:
import pandas as pd

## Useful functions

In [2]:
def split_frame(df):
    """ Clean data frame by splitting it into multiple data frames.
    
        This function will find all the indicies where the column 'd%'
        contains 'd%' and then will create a list of data frames from those
        indicies.
    """
    
    # find index
    filt = df['d%'] == 'd%'
    idx = filt[filt==True].index
    
    # create frames
    df_list = []
    # start
    df_list.append(df.iloc[:idx[0]])
    # med
    for i in range(len(idx)-1):
        df_list.append(df.iloc[idx[i]+1:idx[i+1]])
    # end
    df_list.append(df.iloc[idx[-1]+1:])
    
    return df_list

In [3]:
def save_data(df_list, category, names):
    """ export all data frame to csv """
    
    for df, name in zip(df_list, names):
        df.to_csv('clean_data/' + category + '/' + name + '.csv', sep=',', index=False)

# Anelli

In [4]:
df = pd.read_csv('data/Anelli_1.csv')
df

,d%,Anello minore inferiore,Prezzo,Peso,Fonte,Unnamed: 5,Unnamed: 6
0,01-07,Anello della Prigione del Prigioniero,Anello minore inferiore,Anello,250 mo,-,Guida del Giocatore
1,08-16,Anello dei Sigilli Arcani,Anello minore inferiore,Anello,1.000 mo,-,Guida del Giocatore
2,17-23,Anello della Conoscenza degli Incantesimi I,Anello minore inferiore,Anello,1.500 mo,-,Guida all'Equipaggiamento
3,26-40,Anello di Protezione +1,Anello minore inferiore,Anello,2.000 mo,-,Manuale di Gioco
4,41-47,Anello dell'Avida Tomba,Anello minore inferiore,Anello,2.000 mo,-,Guida all'Equipaggiamento
...,...,...,...,...,...,...,...
111,87-90,Anello dei Tre Desideri,Anello maggiore superiore,Anello,120.000 mo,-,Manuale di Gioco
112,91-93,Anello del Richiamo del Djinni,Anello maggiore superiore,Anello,125.000 mo,-,Manuale di Gioco
113,-,Anello della Psiche Nascosta,Anello maggiore superiore,Anello,160.000 mo,-,Avventure Occulte
114,94-97,Anello del Comando degli Elementi,Anello maggiore superiore,Anello,200.000 mo,-,Manuale di Gioco
115,98-100,Anello Accumula Incantesimi Maggiore,Anello maggiore superiore,Anello,200.000 mo,-,Manuale di Gioco

In [5]:
d = {'d%':df['d%'], 'Oggetto':df['Anello minore inferiore'], 'Prezzo':df['Fonte'], 'Fonte':df['Unnamed: 6']}
clean_df = pd.DataFrame(d)
clean_df

,d%,Oggetto,Prezzo,Fonte
0,01-07,Anello della Prigione del Prigioniero,250 mo,Guida del Giocatore
1,08-16,Anello dei Sigilli Arcani,1.000 mo,Guida del Giocatore
2,17-23,Anello della Conoscenza degli Incantesimi I,1.500 mo,Guida all'Equipaggiamento
3,26-40,Anello di Protezione +1,2.000 mo,Manuale di Gioco
4,41-47,Anello dell'Avida Tomba,2.000 mo,Guida all'Equipaggiamento
...,...,...,...,...
111,87-90,Anello dei Tre Desideri,120.000 mo,Manuale di Gioco
112,91-93,Anello del Richiamo del Djinni,125.000 mo,Manuale di Gioco
113,-,Anello della Psiche Nascosta,160.000 mo,Avventure Occulte
114,94-97,Anello del Comando degli Elementi,200.000 mo,Manuale di Gioco
115,98-100,Anello Accumula Incantesimi Maggiore,200.000 mo,Manuale di Gioco

In [6]:
df_list = split_frame(clean_df)

In [7]:
names = ['Anelli_minori_inferiori', 'Anelli_minori_superiori', 'Anelli_medi_minori', 
        'Anelli_medi_superiori', 'Anelli_maggiori_inferiori', 'Anelli_maggiori_superiori']
save_data(df_list, 'Anelli', names)

# Bacchette

In [8]:
bacchette_df = []
for i in range(10):
    bacchette_df.append(pd.read_csv('data/Bacchette_' + str(i+1) +'.csv'))

In [9]:
# splitting not needed

# look at [8]
bacchette_df[8].tail()

,d%,Bacchetta comune,Prezzo,Fonte
41,96,Spezzare Incantamento,30.000 mo,Manuale di Gioco
42,97-98,Pelle di Pietra,33.500 mo,Manuale di Gioco
43,99,Alleato Planare Inferiore,46.000 mo,Manuale di Gioco
44,100,Ristorare *,71.000 mo,Manuale di Gioco
45,* PuÃƒÂ² dissolvere livelli negativi permanenti,* PuÃƒÂ² dissolvere livelli negativi permanenti,* PuÃƒÂ² dissolvere livelli negativi permanenti,* PuÃƒÂ² dissolvere livelli negativi permanenti

In [10]:
# remove the last row
bacchette_df[8] = bacchette_df[8].iloc[:-1]
bacchette_df[8].tail()

       d%           Bacchetta comune     Prezzo             Fonte
40  94-95                  Ristorare  26.000 mo  Manuale di Gioco
41     96      Spezzare Incantamento  30.000 mo  Manuale di Gioco
42  97-98            Pelle di Pietra  33.500 mo  Manuale di Gioco
43     99  Alleato Planare Inferiore  46.000 mo  Manuale di Gioco
44    100               Ristorare  *  71.000 mo  Manuale di Gioco

In [11]:
# change object name
for df in bacchette_df:
    df.columns = ['d%', 'Oggetto', 'Prezzo', 'Fonte']

In [12]:
# names
names1 = ['Bacchette_comuni_lv' + str(i) for i in range(5)]
names2 = ['Bacchette_non_comuni_lv' + str(i) for i in range(5)]

In [13]:
# save
save_data(bacchette_df[0::2], 'Bacchette', names1)
save_data(bacchette_df[1::2], 'Bacchette', names2)

# Bastoni

In [14]:
bastoni_df = pd.read_csv('data/Bastoni_1.csv')
bastoni_df.head()

,d%,Bastone medio inferiore,Prezzo,Peso,Fonte,Unnamed: 5,Unnamed: 6
0,01Ã¢Â€Â“10,Bastone del Conforto Benedetto,Bastone medio inferiore,Nessuno,7.200 mo,"2,5 kg",Guida all'Equipaggiamento
1,11-20,Bastone dell'Arcano Minore,Bastone medio inferiore,Nessuno,8.000 mo,"2,5 kg",Guida all'Equipaggiamento
2,21-30,Bastone dei Trucchi,Bastone medio inferiore,Nessuno,8.800 mo,"1,5 kg",Guida all'Equipaggiamento
3,31-44,Bastone dell'Esploratore,Bastone medio inferiore,Nessuno,9.600 mo,2 kg,Guida all'Equipaggiamento
4,-,Bastone della Mostrificazione,Bastone medio inferiore,Nessuno,12.000 mo,2 kg,Guida alle Classi

In [15]:
d = {'d%':bastoni_df['d%'], 'Oggetto':bastoni_df['Bastone medio inferiore'],
     'Prezzo':bastoni_df['Fonte'], 'Fonte':bastoni_df['Unnamed: 6']}
bastoni_df = pd.DataFrame(d)
bastoni_df.head()

,d%,Oggetto,Prezzo,Fonte
0,01Ã¢Â€Â“10,Bastone del Conforto Benedetto,7.200 mo,Guida all'Equipaggiamento
1,11-20,Bastone dell'Arcano Minore,8.000 mo,Guida all'Equipaggiamento
2,21-30,Bastone dei Trucchi,8.800 mo,Guida all'Equipaggiamento
3,31-44,Bastone dell'Esploratore,9.600 mo,Guida all'Equipaggiamento
4,-,Bastone della Mostrificazione,12.000 mo,Guida alle Classi

In [22]:
# correct first entry
bastoni_df['d%'].iloc[0] = '01-10'
bastoni_df.head()

      d%                         Oggetto     Prezzo                      Fonte
0  01-10  Bastone del Conforto Benedetto   7.200 mo  Guida all'Equipaggiamento
1  11-20      Bastone dell'Arcano Minore   8.000 mo  Guida all'Equipaggiamento
2  21-30             Bastone dei Trucchi   8.800 mo  Guida all'Equipaggiamento
3  31-44        Bastone dell'Esploratore   9.600 mo  Guida all'Equipaggiamento
4      -   Bastone della Mostrificazione  12.000 mo          Guida alle Classi

In [23]:
# splitting
bastoni_df_list = split_frame(bastoni_df)
len(bastoni_df_list)

4

In [28]:
# save
names = ['Bastoni_medi_inferiori', 'Bastoni_medi_superiori', 'Bastoni_maggiori_inferiori', 
         'Bastoni_maggioni_superiori']
save_data(bastoni_df_list, 'Bastoni', names)

# Pozioni

In [31]:
pozioni_df = []
for i in range(7):
    pozioni_df.append(pd.read_csv('data/Pozioni_' + str(i+1) +'.csv'))

In [34]:
pozioni_df[1].head()

      d% Pozione o olio comune Prezzo             Fonte
0    NaN      Benedire un'Arma  50 mo  Manuale di Gioco
1  05-14   Cura Ferite Leggere  50 mo  Manuale di Gioco
2  15-19  Contrastare Elementi  50 mo  Manuale di Gioco
3  20-27    Ingrandire Persone  50 mo  Manuale di Gioco
4  28-33               Saltare  50 mo  Manuale di Gioco

In [39]:
# correct first row
pozioni_df[1]['d%'].iloc[0] = '01-04'

In [41]:
# change object name
for df in pozioni_df:
    df.columns = ['d%', 'Oggetto', 'Prezzo', 'Fonte']

In [44]:
# names
names1 = ['Pozioni_comuni_lv' + str(i) for i in range(1,4)]
names2 = ['Pozioni_non_comuni_lv' + str(i) for i in range(1,4)]

In [45]:
# save
save_data([pozioni_df[0]], 'Pozioni', ['Pozioni_comuni_lv0'])
save_data(pozioni_df[1::2], 'Pozioni', names1)
save_data(pozioni_df[2::2], 'Pozioni', names2)

# Verghe

In [70]:
verghe_df = pd.read_csv('data/Verghe_1.csv')
verghe_meta_df = []
for i in range(2,5):
    verghe_meta_df.append(pd.read_csv('data/Verghe_' + str(i) + '.csv'))

## Tabella base

In [51]:
verghe_df.head()

,d%,Verga media inferiore,Prezzo,Peso,Fonte,Unnamed: 5,Unnamed: 6
0,01,Verga Metamagica Pietosa Minore,Verga media inferiore,Nessuno,1.500 mo,5 kg,Guida del Giocatore
1,02-34,Metamagica (liv. incantesimo +1) Minore,Verga media inferiore,Nessuno,3.000 mo,"2,5 kg",-
2,-,Verga della Rifocalizzazione,Verga media inferiore,Nessuno,5.000 mo,"0,5 kg",Avventure Occulte
3,35-49,Verga Inamovibile,Verga media inferiore,Nessuno,5.000 mo,"2,5 kg",Manuale di Gioco
4,50-59,Verga della Forza Tonante,Verga media inferiore,Nessuno,5.400 mo,"2,5 kg",Guida all'Equipaggiamento

In [53]:
d = {'d%':verghe_df['d%'], 'Oggetto':verghe_df['Verga media inferiore'],
     'Prezzo':verghe_df['Fonte'], 'Fonte':verghe_df['Unnamed: 6']}
verghe_df = pd.DataFrame(d)
verghe_df.head()

,d%,Oggetto,Prezzo,Fonte
0,01,Verga Metamagica Pietosa Minore,1.500 mo,Guida del Giocatore
1,02-34,Metamagica (liv. incantesimo +1) Minore,3.000 mo,-
2,-,Verga della Rifocalizzazione,5.000 mo,Avventure Occulte
3,35-49,Verga Inamovibile,5.000 mo,Manuale di Gioco
4,50-59,Verga della Forza Tonante,5.400 mo,Guida all'Equipaggiamento

In [54]:
verghe_df = split_frame(verghe_df)
len(verghe_df)

4

In [55]:
# save
names = ['Verghe_medi_inferiori', 'Verga_medi_superiori', 'Verghe_maggiori_inferiori', 
         'Verghe_maggioni_superiori']
save_data(verghe_df, 'Verghe', names)

## Tabella verghe metamagiche

In [71]:
# assign column name
columns = verghe_meta_df[0].iloc[0]
verghe_meta_df = [df.iloc[1:] for df in verghe_meta_df]
for df in verghe_meta_df:
    df.columns = columns

In [76]:
# save
names = ['Verghe_metamagiche_+' + str(i) for i in [1,2,3]]
save_data(verghe_meta_df, 'Verghe', names)